---
tags: [spring,spring boot,maven,github]
projects: [initial]
---
////
markDown中的注释
http://wiselyman.iteye.com/blog/2210250
http://sivalabs.in/2015/11/developing-a-simple-e-commerce-application-from-scratch-to-production-using-springboot/
http://sspai.com/25137
http://www.jianshu.com/p/1e402922ee32/
////
== github技巧

提交快捷键　push ctrl+shift+k

== maven 元素的学习

* groupId定义了项目属于哪个组，这个组往往和项目所在的组织或公司存在关联。譬如在googlecode上建立了一个名为myapp的项目，那么groupId就应该是com.googlecode.myapp
* artifactId定义了当前maven项目在组中唯一的ID，如在前面的groupId为com.googlecode.myapp的例子中，你可能会为不同的子项目(模块)分配artifactId,如:myapp-util,myapp-domain,myapp-web等。
* version指定了项目当前的版本--1.0-SNAPSHOT。SNAPSHOT意为快照，说明该项目还处于开发中，是不稳定的版本。

> maven是一个项目构建工具,利用maven我们不需要手工拷贝包到项目中,只需通过pom.xml文件里的包的描述自动从互联网下载相关依赖包.
若无互联网环境可搭建maven私服(nexus:http://www.sonatype.org/nexus/)
依赖包借助http://mvnrepository.com这个网站来检索

# 手动增加依赖包
[source]
mvn install:install-file -DgroupId=com.oracle "-DartifactId=ojdbc14"
"-Dversion=10.2.0.2.0" "-Dpackaging=jar" "-Dfile=D:\ojdbc14.jar"

此时在pom.xml用如下引入:

[source]
<dependency>
    <groupId>com.oracle</groupId>
    <artifactId>ojdbc14</artifactId>
    <version>10.2.0.2.0</version>
</dependency>


### @RequestMapping

* @RequestMapping是SpringMVC的核心注解,负责访问的url与调用方法之间的映射;
* @RequestMapping可以放在类和方法上;

    *@RequestMapping的属性produces属性控制response返回的形式;*
    *@RequestMapping的属性method属性控制接受访问的类型*

* @ResponseBody(放在方法上或者返回值类型前)将方法参数放置在web body的body中(返回的不是页面而是你所控制的字符)

    *@RequestBody(放在方法参数前)将方法参数放置在web request的body中*

### produces的内容是指定返回的媒体类型让浏览器识别

* 如返回text/plain的话,chrome浏览器下network显示Response的Content-Type:text/plain;
* 如返回application/json的话,chrome浏览器下network显示Response的application/json;

### REST支持的http method(通过@RequestMapping的method属性控制)
* POST:新增
* GET:读取
* PUT/PATCH:更新
* DELETE:删除

添加jackson依赖

jackson-dataformat-xml依赖jackson-bind,这样我们能同时返回xml和json

[source]
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.5.3</version>
</dependency>

若只需返回json数据(大多数项目都是这样),将上面依赖更换为
[source]
 <dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.5.3</version>
</dependency>