logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost/spring-aop-log?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    max-active: 5
    max-idle: 2
    min-idle: 1
    initial-size: 1
    initialize: false
mybatis:
  typeAliasesPackage: com.example.domain
  mapperLocations: classpath*:**/mappers/*.xml


