spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
#\u52A0\u4E0A\u65F6\u95F4\uFF0C\u65F6\u95F4\u624D\u80FD\u5BF9\u4E0A
        time-zone: Asia/Shanghai
    thymeleaf:
      cache: false
## \u662F\u5426\u663E\u793A SQL \u8BED\u53E5
    jpa:
      show-sql: true