#常量定义
demo:
    name: zhanshan
    number: ${random.int}
    secret: ${random.value}
server:
    port: 8080
#加上时间格式
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
#加上时间，时间才能对上
        time-zone: Asia/Shanghai
    profiles:
      active: dev